- job:
    name: glance_store-dsvm-functional-base
    parent: devstack-tox-functional
    description: |
      Base job for devstack-based functional tests for glance_store

      Can only be used directly if a 'functional' testenv is defined
      in tox.ini (which currently is not the case).
    required-projects:
      - openstack/glance_store
    timeout: 4200
    vars:
      devstack_localrc:
        LIBS_FROM_GIT: glance_store
      devstack_services:
        # turn off ceilometer
        ceilometer-acentral: false
        ceilometer-acompute: false
        ceilometer-alarm-evaluator: false
        ceilometer-alarm-notifier: false
        ceilometer-anotification: false
        ceilometer-api: false
        ceilometer-collector: false
      # Hardcode glance_store path so the job can be run on glance patches
      zuul_work_dir: src/opendev.org/openstack/glance_store

- job:
    name: glance_store-dsvm-functional-filesystem
    parent: glance_store-dsvm-functional-base
    vars:
      tox_envlist: functional-filesystem

- job:
    name: glance_store-dsvm-functional-swift
    parent: glance_store-dsvm-functional-base
    required-projects:
      - openstack/swift
    vars:
      tox_envlist: functional-swift
      devstack_services:
        s-account: true
        s-container: true
        s-object: true
        s-proxy: true

- job:
    name: glance_store-tox-cinder-tips-base
    parent: tox
    abstract: true
    description: Abstract job for glance_store vs. cinder
    nodeset: ubuntu-focal
    required-projects:
      - name: openstack/os-brick
      - name: openstack/python-cinderclient

- job:
    name: glance_store-tox-py3-cinder-tips
    parent: glance_store-tox-cinder-tips-base
    description: |
      glance_store py3 unit tests vs. cinder masters
    vars:
      tox_envlist: py3

- job:
    name: glance_store-tox-keystone-tips-base
    parent: tox
    abstract: true
    description: Abstract job for glance_store vs. keystone
    nodeset: ubuntu-focal
    required-projects:
      - name: openstack/keystoneauth
      - name: openstack/python-keystoneclient

- job:
    name: glance_store-tox-py3-keystone-tips
    parent: glance_store-tox-keystone-tips-base
    description: |
      glance_store py3 unit tests vs. keystone masters
    vars:
      tox_envlist: py3

- job:
    name: glance_store-tox-oslo-tips-base
    parent: tox
    abstract: true
    description: Abstract job for glance_store vs. oslo
    nodeset: ubuntu-focal
    required-projects:
      - name: openstack/oslo.concurrency
      - name: openstack/oslo.config
      - name: openstack/oslo.i18n
      - name: openstack/oslo.privsep
      - name: openstack/oslo.rootwrap
      - name: openstack/oslo.serialization
      - name: openstack/oslo.utils
      - name: openstack/oslo.vmware
      - name: openstack/stevedore

- job:
    name: glance_store-tox-py3-oslo-tips
    parent: glance_store-tox-oslo-tips-base
    description: |
      glance_store py3 unit tests vs. oslo masters
    vars:
      tox_envlist: py3

- job:
    name: glance_store-tox-swift-tips-base
    parent: tox
    abstract: true
    description: Abstract job for glance_store vs. swift
    nodeset: ubuntu-focal
    required-projects:
      - name: openstack/python-swiftclient

- job:
    name: glance_store-tox-py3-swift-tips
    parent: glance_store-tox-swift-tips-base
    description: |
      glance_store py3 unit tests vs. swift masters
    vars:
      tox_envlist: py3

- job:
    name: glance_store-src-ceph-tempest
    parent: devstack-plugin-ceph-tempest-py3
    description: |
      Runs tempest tests with the latest glance_store and the Ceph backend
      Former names for this job were:
      * legacy-tempest-dsvm-full-ceph-plugin-src-glance_store
    required-projects:
      - opendev.org/openstack/glance_store
    timeout: 10800
    vars:
      tempest_test_regex: (^tempest\.(api|scenario)|(^cinder_tempest_plugin))

- job:
    name: cross-glance-tox-functional
    parent: openstack-tox
    description: |
      Run cross-project glance functional tests on glance_store.
    vars:
      zuul_work_dir: src/opendev.org/openstack/glance
      tox_envlist: functional
    required-projects:
      - openstack/glance
      - openstack/glance_store

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - cross-glance-tox-functional
        - glance_store-src-ceph-tempest:
            irrelevant-files: &tempest-irrelevant-files
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^.*\.rst$
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
              - ^tox.ini$
    experimental:
      jobs:
        - glance_store-dsvm-functional-filesystem
        - glance_store-dsvm-functional-swift
    periodic:
      jobs:
        # NOTE(rosmaita): we only want the "tips" jobs to be run against
        # master, hence the 'branches' qualifiers below.  Without them, when
        # a stable branch is cut, the tests would be run against the stable
        # branch as well, which is pointless because these libraries are
        # frozen (more or less) in the stable branches.
        #
        # The "tips" jobs can be removed from the stable branch .zuul.yaml
        # files if someone is so inclined, but that would require manual
        # maintenance, so we do not do it by default.  Another option is
        # to define these jobs in the openstack/project-config repo.
        # That would make us less agile in adjusting these tests, so we
        # aren't doing that either.
        - glance_store-tox-py3-cinder-tips:
            branches: master
        - glance_store-tox-py3-keystone-tips:
            branches: master
        - glance_store-tox-py3-oslo-tips:
            branches: master
        - glance_store-tox-py3-swift-tips:
            branches: master
